Repository AY2425S1-CS2113-W12-3/tp, pull requests merged in 2024-10, with the labels that each got.

#47 Add Save and Load Feature
  build.gradle
  src/main/java/wheresmymoney/ExpenseList.java
  src/main/java/wheresmymoney/Parser.java
Labels: type.Task, priority.High

#56 Prepare UG and DG outline
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#68 Add date functionality to Expense
  docs/DeveloperGuide.md
  src/main/java/wheresmymoney/DateUtils.java
  src/main/java/wheresmymoney/Expense.java
  src/main/java/wheresmymoney/ExpenseList.java
  src/main/java/wheresmymoney/Parser.java
  src/main/java/wheresmymoney/command/AddCommand.java
  src/main/java/wheresmymoney/command/EditCommand.java
  src/main/java/wheresmymoney/command/ListCommand.java
  src/test/java/wheresmymoney/ExpenseListTest.java
  src/test/java/wheresmymoney/ExpenseTest.java
Labels: type.Bug, priority.High, severity.High, type.CodeQuality

#77 Fix plantUML class diagram rendering on GitHub pages
  docs/DeveloperGuide.md
  docs/diagrams/images/ExpenseAndExpenseList.png
  docs/diagrams/plantuml/ExpenseAndExpenseList.puml
Labels: type.Bug, priority.High, severity.High, type.Documentation

#75 Add Parser JUnit tests and Parser bugfixes
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/wheresmymoney/Parser.java
  src/test/java/wheresmymoney/ExpenseListTest.java
  src/test/java/wheresmymoney/ParserTest.java
Labels: type.Bug, type.CodeQuality, type.Cs2113CourseTask
