Repository AY2425S1-CS2113-W12-3/tp, pull requests merged in 2024-11, with the labels that each got.

#79 Add spending limits
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/images/CategoryDataAndCategoryTracker.png
  docs/diagrams/images/ExpenseAndExpenseList.png
  docs/diagrams/plantuml/CategoryDataAndCategoryTracker.puml
  docs/diagrams/plantuml/ExpenseAndExpenseList.puml
  src/main/java/wheresmymoney/DateUtils.java
  src/main/java/wheresmymoney/Expense.java
  src/main/java/wheresmymoney/ExpenseList.java
  src/main/java/wheresmymoney/Main.java
  src/main/java/wheresmymoney/Parser.java
  src/main/java/wheresmymoney/category/CategoryData.java
  src/main/java/wheresmymoney/category/CategoryFacade.java
  src/main/java/wheresmymoney/category/CategoryFilter.java
  src/main/java/wheresmymoney/category/CategoryStorage.java
  src/main/java/wheresmymoney/category/CategoryTracker.java
  src/main/java/wheresmymoney/command/AddCommand.java
  src/main/java/wheresmymoney/command/ByeCommand.java
  src/main/java/wheresmymoney/command/Command.java
  src/main/java/wheresmymoney/command/DeleteCommand.java
  src/main/java/wheresmymoney/command/EditCommand.java
  src/main/java/wheresmymoney/command/HelpCommand.java
  src/main/java/wheresmymoney/command/ListCommand.java
  src/main/java/wheresmymoney/command/LoadCommand.java
  src/main/java/wheresmymoney/command/SaveCommand.java
  src/main/java/wheresmymoney/command/SetCommand.java
  src/test/java/wheresmymoney/CategoryDataTest.java
  src/test/java/wheresmymoney/CategoryTrackerTest.java
  src/test/java/wheresmymoney/ExpenseListTest.java
Labels: type.Epic, type.Story, priority.Medium, type.CodeQuality

#85 Add PPP for Kylan (@Progresst-8)
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/images/Category Classes ClassUML.png
  docs/diagrams/images/CategoryDataAndCategoryTracker.png
  docs/diagrams/plantuml/CategoryClasses ClassUML.puml
  docs/diagrams/plantuml/CategoryDataAndCategoryTracker.puml
  docs/team/progresst-8.md
  src/main/java/wheresmymoney/category/CategoryFacade.java
  src/main/java/wheresmymoney/category/CategoryFilter.java
  src/main/java/wheresmymoney/category/CategoryStorage.java
Labels: type.Documentation

#104 Update UG and Help Command with Set feature
  docs/UserGuide.md
  src/main/java/wheresmymoney/command/HelpCommand.java
Labels: type.Documentation

#114 Update Documentation for Milestone 2.0
  MyLogFile.log
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/images/ArchitectureDiagram.png
  docs/diagrams/powerpoint/ArchitectureDiagram.pptx
  src/main/java/wheresmymoney/command/VisualizeCommand.java
  src/main/java/wheresmymoney/visualizer/Visualizer.java
Labels: priority.High, type.Documentation

#105 Update DG again for Milestone 2.0
  docs/DeveloperGuide.md
  docs/diagrams/images/CategoryClasses ClassUML.png
  docs/diagrams/plantuml/CategoryClasses ClassUML.puml
  docs/diagrams/plantuml/ExpenseAndExpenseList.puml
  src/main/java/wheresmymoney/CsvUtils.java
  src/main/java/wheresmymoney/ExpenseList.java
  src/main/java/wheresmymoney/category/CategoryFacade.java
  src/main/java/wheresmymoney/category/CategoryStorage.java
  src/main/java/wheresmymoney/category/CategoryTracker.java
  src/main/java/wheresmymoney/command/EditCommand.java
  src/main/java/wheresmymoney/command/ListCommand.java
Labels: type.Documentation

#118 Update documentation before Test Run
  docs/UserGuide.md
  src/main/java/wheresmymoney/category/CategoryFacade.java
Labels: priority.High, type.Documentation

#174 Update Documentation for v2.1
  docs/UserGuide.md
  docs/diagrams/images/ArchitectureDiagram.png
  docs/diagrams/powerpoint/ArchitectureDiagram.pptx
  docs/team/andrewnguyen4.md
Labels: priority.Medium

#173 Add warning/alert when setting limits
  src/main/java/wheresmymoney/category/CategoryFacade.java
Labels: type.Bug, priority.High, severity.High

#175 Add ExpenseFilterTest
  src/main/java/wheresmymoney/visualizer/Visualizer.java
  src/test/java/wheresmymoney/ExpenseFilterTest.java
Labels: priority.Medium

#171 Fix issues relating to warnings/alerts when saving then loading
  src/main/java/wheresmymoney/ExpenseList.java
  src/main/java/wheresmymoney/category/CategoryFacade.java
  src/main/java/wheresmymoney/category/CategoryStorage.java
Labels: type.Bug, priority.High, severity.High

#172 Fix issues relating to warnings/alerts after edit
  src/main/java/wheresmymoney/category/CategoryData.java
  src/main/java/wheresmymoney/category/CategoryTracker.java
  src/main/java/wheresmymoney/command/EditCommand.java
Labels: type.Bug, priority.High, severity.High

#185 Update Documentation for Milestone 2.1 (PPP, UG, DG)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/images/CategoryClasses ClassUML.png
  docs/diagrams/images/CategoryFacade Add SequenceUML.png
  docs/diagrams/images/CategoryFacade Delete SequenceUML.png
  docs/diagrams/images/CategoryFacade Edit SequenceUML.png
  docs/diagrams/images/CategoryFacade Load SequenceUML.png
  docs/diagrams/images/CategoryFacade Save SequenceUML.png
  docs/diagrams/images/CategoryFacade Set SequenceUML.png
  docs/diagrams/plantuml/CategoryClasses ClassUML.puml
  docs/diagrams/plantuml/CategoryFacade Add SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Delete SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Edit SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Load SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Save SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Set SequenceUML.puml
  docs/team/progresst-8.md
  src/main/java/wheresmymoney/Expense.java
  src/main/java/wheresmymoney/category/CategoryFacade.java
Labels: priority.High, severity.High, type.Documentation

#187 Correct link to category class UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/images/Category Classes ClassUML.png
Labels: priority.High, severity.High, type.Documentation

#189 Update documentation
  docs/AboutUs.md
  docs/team/progresst-8.md
Labels: priority.High, severity.High, type.Documentation

#192 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/images/CategoryFacade Add SequenceUML.png
  docs/diagrams/images/CategoryFacade Delete SequenceUML.png
  docs/diagrams/images/CategoryFacade Edit SequenceUML.png
  docs/diagrams/images/CategoryFacade Load SequenceUML.png
  docs/diagrams/images/CategoryFacade Save SequenceUML.png
  docs/diagrams/images/CategoryFacade Set SequenceUML.png
  docs/diagrams/images/CommandAndExpenseList.png
  docs/diagrams/plantuml/Category Package ObjectUML.puml
  docs/diagrams/plantuml/CategoryFacade Add SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Delete SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Edit SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Load SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Save SequenceUML.puml
  docs/diagrams/plantuml/CategoryFacade Set SequenceUML.puml
  docs/diagrams/plantuml/CommandAndExpenseList.puml
Labels: type.Documentation

#193 Correct UMLs
  docs/diagrams/images/CommandInheritance.png
  docs/diagrams/images/UiToCommand.png
  docs/diagrams/plantuml/CommandInheritance.puml
  docs/diagrams/plantuml/UiToCommand.puml
Labels: priority.High, severity.High, type.Documentation
